import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#04BFBF]`}>
        <div className="fixed top-2 left-2 flex justify-start items-center gap-2">
          <Image
            src={"./icon.svg"}
            width={100}
            height={100}
            className="  w-[50px] h-[50px]"
            alt="icon"
          />
          <h2 className=" uppercase text-4xl text-white font-bold">HEY</h2>
        </div>
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
