/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/wDEMxRZH5gt
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import React from "react";

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export default function AlertBox({
  header = "Notice",
  children,
  message = "are you sure",
  backFunction,
  confirmFunction,
  confirmBtnText = "confirm",
}: {
  header?: string;
  children?: React.ReactNode;
  message?: string;
  confirmFunction: () => void;
  backFunction: () => void;
  confirmBtnText?: string;
}) {
  return (
    <div className="fixed inset-0 flex items-center justify-center z-[10000] bg-black bg-opacity-50">
      <div className="bg-white dark:bg-gray-900 rounded-lg shadow-lg p-6 max-w-md w-full">
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-lg font-medium text-gray-900 dark:text-gray-100">
            {header}
          </h3>
          <button
            onClick={() => backFunction()}
            className="text-gray-500 hover:text-gray-700 dark:hover:text-gray-300 focus:outline-none"
          >
            <XIcon className="h-5 w-5" />
          </button>
        </div>
        <p className="text-gray-700 dark:text-gray-400 mb-4">{message}</p>
        {children}
        <div className="flex justify-between">
          <button
            onClick={() => backFunction()}
            className="bg-gray-900 hover:bg-gray-800 text-white px-4 py-2 rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 dark:bg-gray-500 dark:hover:bg-gray-400 dark:focus:ring-gray-300 dark:focus:ring-offset-gray-900"
          >
            Close
          </button>
          <button
            onClick={() => confirmFunction()}
            className="bg-gray-900 hover:bg-gray-800 text-white px-4 py-2 rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 dark:bg-gray-500 dark:hover:bg-gray-400 dark:focus:ring-gray-300 dark:focus:ring-offset-gray-900"
          >
            {confirmBtnText}
          </button>
        </div>
      </div>
    </div>
  );
}

function XIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );
}
