"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/tvqFjNysW3Z
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
const getOrderByUserId = async (id: string) => {
  const response = await axios.get(
    `http://54.167.15.95:3001/orders/byUserId/${id}`
  );
  if (response.status === 201) {
    return response.data;
  } else {
    return console.log("error in fetcing order for user...");
  }
};
import { calculateTotal } from "@/app/libs/cartFunctions";
import { convertDateTime } from "@/app/libs/dateTimeFilter";
import { totalPriceFormat } from "@/app/libs/globalsFuns";
import { useUser } from "@/app/store";
import { Button } from "@/components/ui/button";
import { Order } from "@/types/orderTypes";
import axios from "axios";
import Link from "next/link";
import { useEffect, useState } from "react";

export function Orders() {
  const [orders, setOrders] = useState<Order[] | null>(null);
  const user = useUser((state) => state.user);

  useEffect(() => {
    const fetch_orders = async () => {
      const orders = await getOrderByUserId(user?.id as string);
      setOrders(orders);
    };
    fetch_orders();
  }, []);
  return (
    <div className="bg-white dark:bg-gray-950 h-full shadow-sm">
      <div className="p-6">
        <h2 className="text-2xl font-semibold mb-4">Pending Orders</h2>
        <div className="grid gap-4">
          {orders &&
            orders.map((order, index) => (
              <div
                className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4"
                key={index}
              >
                <div className="flex justify-between items-center mb-2">
                  <span className="font-medium">Order #{order.orderCode}</span>
                  <span className="text-gray-500 dark:text-gray-400 text-sm">
                    {convertDateTime(order.orderTime)}
                  </span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="font-medium">
                    {totalPriceFormat(calculateTotal(order.products))}mmk
                  </span>
                  <div className="flex items-center gap-2">
                    <Button size="sm" variant="outline">
                      <Link href={`/home/orders/${order.id}`}>
                        View Details
                      </Link>
                    </Button>
                    {/* <Button
                      className="bg-red-500 hover:bg-red-600 text-white"
                      size="sm"
                      variant="outline"
                    >
                      Cancel Order
                    </Button> */}
                  </div>
                </div>
              </div>
            ))}
          {/* <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4">
            <div className="flex justify-between items-center mb-2">
              <span className="font-medium">Order #5678</span>
              <span className="text-gray-500 dark:text-gray-400 text-sm">
                May 10, 2024
              </span>
            </div>
            <div className="flex justify-between items-center">
              <span className="font-medium">$49.99</span>
              <div className="flex items-center gap-2">
                <Button size="sm" variant="outline">
                  View Details
                </Button>
                <Button
                  className="bg-red-500 hover:bg-red-600 text-white"
                  size="sm"
                  variant="outline"
                >
                  Cancel Order
                </Button>
              </div>
            </div>
          </div> */}
          {/* <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4">
            <div className="flex justify-between items-center mb-2">
              <span className="font-medium">Order #9012</span>
              <span className="text-gray-500 dark:text-gray-400 text-sm">
                May 9, 2024
              </span>
            </div>
            <div className="flex justify-between items-center">
              <span className="font-medium">$74.99</span>
              <div className="flex items-center gap-2">
                <Button size="sm" variant="outline">
                  View Details
                </Button>
                <Button
                  className="bg-red-500 hover:bg-red-600 text-white"
                  size="sm"
                  variant="outline"
                >
                  Cancel Order
                </Button>
              </div>
            </div>
          </div> */}
        </div>
      </div>
    </div>
  );
}
